"""empty message

Revision ID: 1fe8d7cbe7b5
Revises: a5bd4a634902
Create Date: 2018-05-27 22:05:31.741574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe8d7cbe7b5'
down_revision = 'a5bd4a634902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancel_vc_order_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancel_vc_order_logs_order_id'), 'cancel_vc_order_logs', ['order_id'], unique=False)
    op.create_table('question_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_category_datachange_lasttime'), 'question_category', ['datachange_lasttime'], unique=False)
    op.create_table('question_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_category_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_category_id'], ['question_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_answer_datachange_lasttime'), 'question_answer', ['datachange_lasttime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_answer_datachange_lasttime'), table_name='question_answer')
    op.drop_table('question_answer')
    op.drop_index(op.f('ix_question_category_datachange_lasttime'), table_name='question_category')
    op.drop_table('question_category')
    op.drop_index(op.f('ix_cancel_vc_order_logs_order_id'), table_name='cancel_vc_order_logs')
    op.drop_table('cancel_vc_order_logs')
    # ### end Alembic commands ###
