"""empty message

Revision ID: 2c2c40b53f71
Revises: 1fe8d7cbe7b5
Create Date: 2018-05-27 22:29:21.137821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c2c40b53f71'
down_revision = '1fe8d7cbe7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autotest_Interface',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=True),
    sa.Column('interface_name', sa.String(length=200), nullable=False),
    sa.Column('interface_url', sa.String(length=200), nullable=False),
    sa.Column('interface_header', mysql.JSON(), nullable=True),
    sa.Column('interface_body', mysql.JSON(), nullable=True),
    sa.Column('interface_method', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_Interface_datachange_lasttime'), 'autotest_Interface', ['datachange_lasttime'], unique=False)
    op.create_index(op.f('ix_autotest_Interface_interface_name'), 'autotest_Interface', ['interface_name'], unique=False)
    op.create_table('autotest_UI_testcase',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('testcase_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_UI_testcase_datachange_lasttime'), 'autotest_UI_testcase', ['datachange_lasttime'], unique=False)
    op.create_table('autotest_interface_testcase',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('interface_url', sa.String(length=255), nullable=False),
    sa.Column('testcase_name', sa.String(length=200), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('testcase_method', sa.String(length=200), nullable=False),
    sa.Column('testcase_header', mysql.JSON(), nullable=True),
    sa.Column('testcase_body', mysql.JSON(), nullable=True),
    sa.Column('testcase_verification', mysql.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_interface_testcase_datachange_lasttime'), 'autotest_interface_testcase', ['datachange_lasttime'], unique=False)
    op.create_table('autotest_module',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('module_testers', sa.String(length=50), nullable=False),
    sa.Column('module_developer', sa.String(length=50), nullable=False),
    sa.Column('module_version', sa.String(length=100), nullable=False),
    sa.Column('module_desc', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_module_datachange_lasttime'), 'autotest_module', ['datachange_lasttime'], unique=False)
    op.create_index(op.f('ix_autotest_module_project_id'), 'autotest_module', ['project_id'], unique=False)
    op.create_table('autotest_project',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_name', sa.String(length=50), nullable=False),
    sa.Column('project_testers', sa.String(length=50), nullable=False),
    sa.Column('project_developer', sa.String(length=50), nullable=False),
    sa.Column('project_version', sa.String(length=100), nullable=False),
    sa.Column('project_desc', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_project_datachange_lasttime'), 'autotest_project', ['datachange_lasttime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autotest_project_datachange_lasttime'), table_name='autotest_project')
    op.drop_table('autotest_project')
    op.drop_index(op.f('ix_autotest_module_project_id'), table_name='autotest_module')
    op.drop_index(op.f('ix_autotest_module_datachange_lasttime'), table_name='autotest_module')
    op.drop_table('autotest_module')
    op.drop_index(op.f('ix_autotest_interface_testcase_datachange_lasttime'), table_name='autotest_interface_testcase')
    op.drop_table('autotest_interface_testcase')
    op.drop_index(op.f('ix_autotest_UI_testcase_datachange_lasttime'), table_name='autotest_UI_testcase')
    op.drop_table('autotest_UI_testcase')
    op.drop_index(op.f('ix_autotest_Interface_interface_name'), table_name='autotest_Interface')
    op.drop_index(op.f('ix_autotest_Interface_datachange_lasttime'), table_name='autotest_Interface')
    op.drop_table('autotest_Interface')
    # ### end Alembic commands ###
