"""empty message

Revision ID: 5e6bbc7711c5
Revises: 2c2c40b53f71
Create Date: 2018-07-08 18:12:13.112114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e6bbc7711c5'
down_revision = '2c2c40b53f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autotest_system_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('value', mysql.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.add_column('autotest_Interface', sa.Column('interface_desc', sa.Text(), nullable=True))
    op.add_column('autotest_Interface', sa.Column('interface_query', mysql.JSON(), nullable=True))
    op.add_column('autotest_interface_testcase', sa.Column('testcase_query', mysql.JSON(), nullable=True))
    op.add_column('autotest_testcasegroup', sa.Column('runner_setting_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autotest_testcasegroup', 'runner_setting_id')
    op.drop_column('autotest_interface_testcase', 'testcase_query')
    op.drop_column('autotest_Interface', 'interface_query')
    op.drop_column('autotest_Interface', 'interface_desc')
    op.drop_table('autotest_system_setting')
    # ### end Alembic commands ###
