"""empty message

Revision ID: a5bd4a634902
Revises: 
Create Date: 2018-05-27 13:44:59.305695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5bd4a634902'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autotest_report',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('testgroup_id', sa.BigInteger(), nullable=False),
    sa.Column('result', sa.BOOLEAN(), nullable=True),
    sa.Column('fail', mysql.JSON(), nullable=True),
    sa.Column('error', mysql.JSON(), nullable=True),
    sa.Column('success', mysql.JSON(), nullable=True),
    sa.Column('total', sa.BigInteger(), nullable=True),
    sa.Column('result_log', sa.Text(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_report_datachange_lasttime'), 'autotest_report', ['datachange_lasttime'], unique=False)
    op.create_table('autotest_result',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('testcase_testgroup_id', sa.BigInteger(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_result_datachange_lasttime'), 'autotest_result', ['datachange_lasttime'], unique=False)
    op.create_table('autotest_scheduledtask',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_name', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('testcase_id', sa.BigInteger(), nullable=False),
    sa.Column('task_desc', sa.String(length=200), nullable=False),
    sa.Column('time_interval', sa.Integer(), nullable=False),
    sa.Column('last_execution_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('next_execution_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('task_result', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_scheduledtask_datachange_lasttime'), 'autotest_scheduledtask', ['datachange_lasttime'], unique=False)
    op.create_index(op.f('ix_autotest_scheduledtask_module_id'), 'autotest_scheduledtask', ['module_id'], unique=False)
    op.create_index(op.f('ix_autotest_scheduledtask_testcase_id'), 'autotest_scheduledtask', ['testcase_id'], unique=False)
    op.create_table('autotest_testcase_testgroup',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('testcase_group_id', sa.BigInteger(), nullable=False),
    sa.Column('testcase_id', sa.BigInteger(), nullable=False),
    sa.Column('testcase_execution_order', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_testcase_testgroup_datachange_lasttime'), 'autotest_testcase_testgroup', ['datachange_lasttime'], unique=False)
    op.create_index(op.f('ix_autotest_testcase_testgroup_testcase_execution_order'), 'autotest_testcase_testgroup', ['testcase_execution_order'], unique=False)
    op.create_index(op.f('ix_autotest_testcase_testgroup_testcase_group_id'), 'autotest_testcase_testgroup', ['testcase_group_id'], unique=False)
    op.create_index(op.f('ix_autotest_testcase_testgroup_testcase_id'), 'autotest_testcase_testgroup', ['testcase_id'], unique=False)
    op.create_table('autotest_testcase_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type_code', sa.BigInteger(), nullable=False),
    sa.Column('type_name', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_testcase_type_type_code'), 'autotest_testcase_type', ['type_code'], unique=False)
    op.create_table('autotest_testcasegroup',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('testcase_group_name', sa.String(length=200), nullable=False),
    sa.Column('testcase_type', sa.BigInteger(), nullable=False),
    sa.Column('testcase_desc', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_testcasegroup_datachange_lasttime'), 'autotest_testcasegroup', ['datachange_lasttime'], unique=False)
    op.create_index(op.f('ix_autotest_testcasegroup_module_id'), 'autotest_testcasegroup', ['module_id'], unique=False)
    op.create_index(op.f('ix_autotest_testcasegroup_testcase_type'), 'autotest_testcasegroup', ['testcase_type'], unique=False)
    op.create_table('autotest_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('login_name', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('datachange_lasttime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autotest_user_datachange_lasttime'), 'autotest_user', ['datachange_lasttime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autotest_user_datachange_lasttime'), table_name='autotest_user')
    op.drop_table('autotest_user')
    op.drop_index(op.f('ix_autotest_testcasegroup_testcase_type'), table_name='autotest_testcasegroup')
    op.drop_index(op.f('ix_autotest_testcasegroup_module_id'), table_name='autotest_testcasegroup')
    op.drop_index(op.f('ix_autotest_testcasegroup_datachange_lasttime'), table_name='autotest_testcasegroup')
    op.drop_table('autotest_testcasegroup')
    op.drop_index(op.f('ix_autotest_testcase_type_type_code'), table_name='autotest_testcase_type')
    op.drop_table('autotest_testcase_type')
    op.drop_index(op.f('ix_autotest_testcase_testgroup_testcase_id'), table_name='autotest_testcase_testgroup')
    op.drop_index(op.f('ix_autotest_testcase_testgroup_testcase_group_id'), table_name='autotest_testcase_testgroup')
    op.drop_index(op.f('ix_autotest_testcase_testgroup_testcase_execution_order'), table_name='autotest_testcase_testgroup')
    op.drop_index(op.f('ix_autotest_testcase_testgroup_datachange_lasttime'), table_name='autotest_testcase_testgroup')
    op.drop_table('autotest_testcase_testgroup')
    op.drop_index(op.f('ix_autotest_scheduledtask_testcase_id'), table_name='autotest_scheduledtask')
    op.drop_index(op.f('ix_autotest_scheduledtask_module_id'), table_name='autotest_scheduledtask')
    op.drop_index(op.f('ix_autotest_scheduledtask_datachange_lasttime'), table_name='autotest_scheduledtask')
    op.drop_table('autotest_scheduledtask')
    op.drop_index(op.f('ix_autotest_result_datachange_lasttime'), table_name='autotest_result')
    op.drop_table('autotest_result')
    op.drop_index(op.f('ix_autotest_report_datachange_lasttime'), table_name='autotest_report')
    op.drop_table('autotest_report')
    # ### end Alembic commands ###
