"""empty message

Revision ID: dbbc7cdfa551
Revises: 5e6bbc7711c5
Create Date: 2018-07-18 13:26:12.222580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbc7cdfa551'
down_revision = '5e6bbc7711c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancel_vc_order_logs', sa.Column('datachange_createtime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cancel_vc_order_logs', 'datachange_createtime')
    # ### end Alembic commands ###
